/**
 * wasm_codegen.c - WebAssembly code generation
 */

#include "wasm_codegen.h"
#include "wasm_emit.h"
#include "../common/util.h"
#include "../common/list.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

static int function_returns_void(IRFunction *func);

// Check if module needs a function table (for indirect calls)
static bool module_needs_table(IRModule *module) {
    if (!module || !module->functions) return false;
    
    for (size_t fi = 0; fi < list_size(module->functions); fi++) {
        IRFunction *func = list_get(module->functions, fi);
        if (!func || !func->blocks) continue;
        
        for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
            IRBasicBlock *block = list_get(func->blocks, bi);
            if (!block || !block->instructions) continue;
            
            for (size_t i = 0; i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr) {
                    if (instr->opcode == IR_CALL_INDIRECT || instr->opcode == IR_LOAD_FUNC_ADDR) {
                        return true;
                    }
                }
            }
        }
    }
    return false;
}

// Find a function's index in the module's function list
static int find_function_index(IRModule *module, const char *name) {
    if (!module || !module->functions || !name) return 0;
    
    for (size_t i = 0; i < list_size(module->functions); i++) {
        IRFunction *func = list_get(module->functions, i);
        if (func && func->name && strcmp(func->name, name) == 0) {
            return (int)i;
        }
    }
    return 0;  // Default to first function if not found
}

// Current module being compiled (needed for function index lookup)
static IRModule *current_module = NULL;

// Local variable tracking: maps stack offsets to WASM local indices
#define MAX_LOCALS 256
typedef struct {
    int offset;
    int local_index;
} LocalVar;
static LocalVar local_vars[MAX_LOCALS];
static int local_var_count = 0;
static int next_local_index = 0;  // Will be set to param_count + 1

// Static temp local indices for ARM64 IR instruction handling
static int temp_local_for_save_x8 = -1;
static int temp_local_for_x20 = -1;

// Stack pointer for local arrays - starts at 65536 (64KB)
// NOTE: Defined in runtime.c to allow linking when compiler compiles itself
extern int wasm_stack_ptr;

static void reset_local_vars(int param_count) {
    local_var_count = 0;
    next_local_index = param_count;  // Start locals after parameters
    // Reset temp locals for new function
    temp_local_for_save_x8 = -1;
    temp_local_for_x20 = -1;
}

static void reset_stack_ptr(void) {
    wasm_stack_ptr = 65536;  // Reset to 64KB base
}

static int get_or_create_local(int offset) {
    // Check if we already assigned a local for this offset
    for (int i = 0; i < local_var_count; i++) {
        if (local_vars[i].offset == offset) {
            return local_vars[i].local_index;
        }
    }
    // Assign a new local
    if (local_var_count < MAX_LOCALS) {
        local_vars[local_var_count].offset = offset;
        local_vars[local_var_count].local_index = next_local_index;
        local_var_count++;
        return next_local_index++;
    }
    return 0;  // Fallback
}

// Create WASM codegen context
WasmContext *wasm_context_create(FILE *out) {
    WasmContext *ctx = xmalloc(sizeof(WasmContext));
    ctx->out = out;
    ctx->func_index = 0;
    ctx->string_index = 0;
    ctx->local_index = 0;
    ctx->label_count = 0;
    ctx->memory_pages = 2;
    ctx->has_printf = false;
    ctx->has_putchar = false;
    ctx->stack_depth = 0;
    ctx->needs_table = false;
    return ctx;
}

void wasm_context_destroy(WasmContext *ctx) {
    if (ctx) free(ctx);
}

void wasm_emit_module_header(WasmContext *ctx) {
    wasm_emit(ctx, "(module\n");
    wasm_emit_comment(ctx, "Generated by c-compiler WASM backend");
    wasm_emit(ctx, "\n");
}

void wasm_emit_module_footer(WasmContext *ctx) {
    wasm_emit(ctx, ")\n");
}

void wasm_emit_memory(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, "(memory (export \"memory\") %d)\n", ctx->memory_pages);
    wasm_emit(ctx, "\n");
}

void wasm_emit_table(WasmContext *ctx, IRModule *module) {
    if (!ctx->needs_table) return;
    
    // Count functions for table size
    int func_count = 0;
    if (module && module->functions) {
        func_count = (int)list_size(module->functions);
    }
    if (func_count == 0) func_count = 1;  // At least one slot
    
    wasm_emit_comment(ctx, "Function table for indirect calls");
    wasm_emit_indented(ctx, 1, "(table %d funcref)\n", func_count);
    
    // Emit table elements (function indices)
    wasm_emit_indented(ctx, 1, "(elem (i32.const 0)");
    if (module && module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            if (func && func->name) {
                wasm_emit(ctx, " $%s", func->name);
            }
        }
    }
    wasm_emit(ctx, ")\n");
    wasm_emit(ctx, "\n");
}

void wasm_emit_globals(WasmContext *ctx, IRModule *module) {
    if (!module || !module->globals || list_size(module->globals) == 0) return;
    
    wasm_emit_comment(ctx, "Global variables");
    for (size_t i = 0; i < list_size(module->globals); i++) {
        IRGlobal *global = list_get(module->globals, i);
        if (global->initializer && global->initializer->kind == IR_VALUE_INT) {
            wasm_emit_indented(ctx, 1, "(global $%s (mut i32) (i32.const %lld))\n", 
                             global->name, global->initializer->data.int_val);
        } else {
            // Zero-initialized global
            wasm_emit_indented(ctx, 1, "(global $%s (mut i32) (i32.const 0))\n", global->name);
        }
    }
    wasm_emit(ctx, "\n");
}

void wasm_emit_imports(WasmContext *ctx) {
    if (ctx->has_printf || ctx->has_putchar) {
        wasm_emit_comment(ctx, "Imports");
        if (ctx->has_printf) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"printf\" (func $printf (param i32 i32 i32 i32 i32) (result i32)))\n");
        }
        if (ctx->has_putchar) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"putchar\" (func $putchar (param i32) (result i32)))\n");
        }
        wasm_emit(ctx, "\n");
    }
}

void wasm_emit_exports(WasmContext *ctx, IRModule *module) {
    if (!module || !module->functions) return;
    wasm_emit_comment(ctx, "Exports");
    for (size_t i = 0; i < list_size(module->functions); i++) {
        IRFunction *func = list_get(module->functions, i);
        if (strcmp(func->name, "main") == 0) {
            wasm_emit_indented(ctx, 1, "(export \"main\" (func $main))\n");
            wasm_emit_indented(ctx, 1, "(export \"_main\" (func $main))\n");
        } else {
            wasm_emit_indented(ctx, 1, "(export \"%s\" (func $%s))\n", func->name, func->name);
            wasm_emit_indented(ctx, 1, "(export \"_%s\" (func $%s))\n", func->name, func->name);
        }
    }
}

static int function_returns_void(IRFunction *func) {
    if (!func || !func->blocks) return 0;
    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        for (size_t i = 0; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr->opcode == IR_RET_VOID) return 1;
        }
    }
    return 0;
}

void wasm_emit_function_header(WasmContext *ctx, IRFunction *func) {
    if (!func) return;
    int param_count = 0;
    if (func->blocks) {
        for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
            IRBasicBlock *block = list_get(func->blocks, bi);
            if (!block || !block->instructions) continue;
            for (size_t i = 0; i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr && instr->opcode == IR_STORE_PARAM) {
                    int idx = instr->result->data.int_val;
                    if (idx >= 0 && idx >= param_count) param_count = idx + 1;
                }
            }
        }
    }
    if (param_count > 4) param_count = 4;
    
    int returns_void = function_returns_void(func);
    wasm_emit_indented(ctx, 1, "(func $%s", func->name);
    for (int i = 0; i < param_count; i++) wasm_emit(ctx, " (param $%d i32)", i);
    if (!returns_void) wasm_emit(ctx, " (result i32)");
    wasm_emit(ctx, "\n");
    for (int i = param_count; i < 8; i++) wasm_emit_indented(ctx, 2, "(local $%d i32)\n", i);
}

void wasm_emit_function_footer(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, ")\n");
}

// Emit a value
static void emit_value(WasmContext *ctx, IRValue *val) {
    if (!ctx || !val) return;
    if (val->emitted) return;
    
    switch (val->kind) {
        case IR_VALUE_INT:
            wasm_emit_instr(ctx, "i32.const %lld", val->data.int_val);
            val->emitted = true;
            break;
        case IR_VALUE_FLOAT:
            wasm_emit_instr(ctx, "f64.const %f", val->data.float_val);
            val->emitted = true;
            break;
        case IR_VALUE_PTR:
        case IR_VALUE_STRING:
            wasm_emit_instr(ctx, "i32.const %d", val->string_index * 256);
            val->emitted = true;
            break;
        default:
            if (val->param_reg >= 0 && val->param_reg < 8) {
                // This is a parameter
                wasm_emit_instr(ctx, "local.get $%d", val->param_reg);
            } else if (val->param_reg == -2) {
                // This is a local variable - map offset to local index
                int local = get_or_create_local(val->offset);
                wasm_emit_instr(ctx, "local.get $%d", local);
            } else {
                wasm_emit_instr(ctx, "local.get $0");
            }
            val->emitted = true;
            break;
    }
}

// Emit single instruction
static void emit_instr(WasmContext *ctx, IRInstruction *instr) {
    if (!ctx || !instr) return;
    
    switch (instr->opcode) {
        case IR_CONST_INT:
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                wasm_emit_instr(ctx, "i32.const %lld", instr->result->data.int_val);
                instr->result->emitted = true;
            }
            break;
            
        case IR_ADD:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.add");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_SUB:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.sub");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_MUL:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.mul");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_DIV:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.div_s");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_MOD:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.rem_s");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_AND:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.and");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_OR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.or");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_XOR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.xor");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_SHL:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shl");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_SHR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shr_s");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_NOT:
            if (instr->num_args >= 1) {
                emit_value(ctx, instr->args[0]);
                wasm_emit_instr(ctx, "i32.eqz");
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_CMP_LT:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.lt_s");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_CMP_GT:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.gt_s");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_CMP_LE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.le_s");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_CMP_GE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.ge_s");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_CMP_EQ:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.eq");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_CMP_NE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.ne");
            if (instr->result) instr->result->emitted = true;
            break;
            
        case IR_LOAD:
            if (instr->num_args > 0) emit_value(ctx, instr->args[0]);
            wasm_emit_instr(ctx, "i32.load");
            if (instr->result) instr->result->emitted = true;  // Mark result as on stack
            break;
            
        case IR_LOAD_EXTERNAL:
            // Load value of global variable
            if (instr->label) {
                wasm_emit_instr(ctx, "global.get $%s", instr->label);
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_STORE:
            // WASM i32.store expects: address, value (value on top of stack)
            // So emit address first, then value
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);  // address
                emit_value(ctx, instr->args[1]);  // value
                wasm_emit_instr(ctx, "i32.store");
            }
            break;
            
        case IR_LOAD_STACK:
            if (instr->result) {
                int local;
                if (instr->result->param_reg >= 0) {
                    // This is a parameter
                    local = instr->result->param_reg;
                } else {
                    // This is a local variable - map offset to local index
                    local = get_or_create_local(instr->result->offset);
                }
                wasm_emit_instr(ctx, "local.get $%d", local);
                instr->result->emitted = true;
            }
            break;
            
        case IR_STORE_STACK:
            if (instr->result) {
                // Store value from stack to local variable
                // The value should already be on the stack from previous instructions
                int local;
                if (instr->result->param_reg >= 0) {
                    // This is a parameter
                    local = instr->result->param_reg;
                } else {
                    // This is a local variable - map offset to local index
                    local = get_or_create_local(instr->result->offset);
                }
                wasm_emit_instr(ctx, "local.set $%d", local);
            }
            break;
            
        case IR_CALL:
            if (instr->label) {
                if (strcmp(instr->label, "printf") == 0) ctx->has_printf = true;
                else if (strcmp(instr->label, "putchar") == 0) ctx->has_putchar = true;
                for (int i = 0; i < instr->num_args && i < 5; i++) {
                    if (instr->args[i]) emit_value(ctx, instr->args[i]);
                }
                wasm_emit_instr(ctx, "call $%s", instr->label);
                // Mark the result as emitted (it's on the stack now)
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_LOAD_FUNC_ADDR:
            // Load function address (index in function table)
            // For WASM, we push the function's table index onto the stack
            if (instr->label) {
                // Find the function's index in the module
                int func_idx = find_function_index(current_module, instr->label);
                wasm_emit_instr(ctx, "i32.const %d", func_idx);
                if (instr->result) {
                    instr->result->emitted = true;
                }
            }
            break;
            
        case IR_CALL_INDIRECT: {
            // Indirect call through function pointer
            // args[0] = function pointer (table index), args[1-3] = arguments
            // For WASM: push arguments, then call_indirect
            
            // Count parameters (excluding the function pointer at args[0])
            int param_count = 0;
            for (int i = 1; i < instr->num_args && i < 5; i++) {
                if (instr->args[i]) param_count++;
            }
            
            // Load arguments onto stack
            for (int i = 1; i < instr->num_args && i < 5; i++) {
                if (instr->args[i]) emit_value(ctx, instr->args[i]);
            }
            
            // The function pointer (table index) should already be on the stack
            // from IR_LOAD_FUNC_ADDR or loaded from a variable
            if (instr->args[0]) {
                emit_value(ctx, instr->args[0]);
            }
            
            // Build the call_indirect signature based on parameter count
            // For now, assume all params are i32 and return type is i32
            char sig[256] = "";
            strcpy(sig, "call_indirect");
            for (int i = 0; i < param_count; i++) {
                if (i == 0) strcat(sig, " (param i32)");
                else strcat(sig, " i32");
            }
            strcat(sig, " (result i32)");
            
            wasm_emit_instr(ctx, "%s", sig);
            
            if (instr->result) {
                instr->result->emitted = true;
            }
            break;
        }
            
        case IR_RET:
            if (instr->num_args > 0 && instr->args[0]) emit_value(ctx, instr->args[0]);
            wasm_emit_instr(ctx, "return");
            break;
            
        case IR_RET_VOID:
            wasm_emit_instr(ctx, "return");
            break;

        case IR_STORE_INDIRECT:
            // Store value to memory at address
            // Stack: [address, value] -> []
            // In WASM: i32.store
            wasm_emit_instr(ctx, "i32.store");
            break;

        case IR_LEA:
            // Load effective address (sp + offset)
            // For WASM, emit the address stored for this allocation
            if (instr->result && instr->result->offset >= 0) {
                int local = get_or_create_local(instr->result->offset);
                wasm_emit_instr(ctx, "local.get $%d", local);
            } else {
                wasm_emit_instr(ctx, "i32.const 0");
            }
            break;
            
        case IR_ALLOCA:
            // Allocate stack space for local variables/arrays
            // For WASM, allocate from linear memory and store address in a local
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                int size = instr->result->data.int_val;
                if (size <= 0) size = 8;  // Default size
                
                // Allocate space and get address
                int addr = wasm_stack_ptr;
                wasm_stack_ptr += size;
                
                // Round up to 8-byte alignment
                wasm_stack_ptr = (wasm_stack_ptr + 7) & ~7;
                
                // Store the address in a local
                if (instr->result->offset >= 0) {
                    int local = get_or_create_local(instr->result->offset);
                    wasm_emit_instr(ctx, "i32.const %d", addr);
                    wasm_emit_instr(ctx, "local.set $%d", local);
                }
            }
            break;

        default:
            // Skip other instructions
            break;
    }
}

void wasm_emit_function_body(WasmContext *ctx, IRFunction *func) {
    if (!func || !func->blocks) return;

    // Determine parameter count for this function
    int param_count = 0;
    if (func->blocks) {
        for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
            IRBasicBlock *block = list_get(func->blocks, bi);
            if (!block || !block->instructions) continue;
            for (size_t i = 0; i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr && instr->opcode == IR_STORE_PARAM) {
                    int idx = instr->result->data.int_val;
                    if (idx >= 0 && idx >= param_count) param_count = idx + 1;
                }
            }
        }
    }

    // Reset local variable tracking with this function's parameter count
    reset_local_vars(param_count);

    wasm_set_indent(ctx, 2);
    int returns_void = function_returns_void(func);

    wasm_emit_indented(ctx, 2, "(block $exit%s\n", returns_void ? "" : " (result i32)");

    // Collect all instructions into a flat list for easier processing
    #define MAX_INSTRS 1024
    IRInstruction *all_instrs[MAX_INSTRS];
    int instr_count = 0;

    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        for (size_t i = 0; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr_count < MAX_INSTRS) {
                all_instrs[instr_count++] = instr;
            }
        }
    }

    // Process instructions, converting control flow to WASM if/else blocks and loops
    int i = 0;
    while (i < instr_count) {
        IRInstruction *instr = all_instrs[i];

        if (instr->opcode == IR_LABEL) {
            // Check if this label is the target of a backward jump (loop)
            int is_loop = 0;
            const char *label_name = instr->label;
            if (label_name) {
                // Look for a JMP that targets this label
                for (int j = i + 1; j < instr_count; j++) {
                    if (all_instrs[j]->opcode == IR_JMP && all_instrs[j]->label &&
                        strcmp(all_instrs[j]->label, label_name) == 0) {
                        is_loop = 1;
                        break;
                    }
                }
            }
            
            if (is_loop) {
                // This is a while loop - emit WASM loop construct
                // Find the JMP_IF that exits the loop
                int jmp_if_idx = -1;
                int jmp_idx = -1;
                for (int j = i + 1; j < instr_count; j++) {
                    if (all_instrs[j]->opcode == IR_JMP_IF) {
                        jmp_if_idx = j;
                    }
                    if (all_instrs[j]->opcode == IR_JMP && all_instrs[j]->label &&
                        strcmp(all_instrs[j]->label, label_name) == 0) {
                        jmp_idx = j;
                        break;
                    }
                }
                
                if (jmp_if_idx >= 0 && jmp_idx < instr_count - 1) {
                    // Emit loop structure
                    wasm_emit_indented(ctx, 2, "(loop $continue\n");
                    
                    // Emit condition check instructions (between label and JMP_IF)
                    for (int j = i + 1; j < jmp_if_idx; j++) {
                        emit_instr(ctx, all_instrs[j]);
                    }
                    
                    // Emit if with body and branch back
                    wasm_emit_indented(ctx, 2, "  (if\n");
                    wasm_emit_indented(ctx, 2, "    (then\n");
                    
                    // Emit body (between JMP_IF and JMP)
                    int j = jmp_if_idx + 1;
                    int last_was_restore = 0;
                    while (j < jmp_idx) {
                        emit_instr(ctx, all_instrs[j]);
                        last_was_restore = (all_instrs[j]->opcode == IR_RESTORE_X8_RESULT);
                        j++;
                    }
                    if (last_was_restore) {
                        wasm_emit_instr(ctx, "drop");
                    }
                    
                    // Branch back to loop start
                    wasm_emit_instr(ctx, "br $continue");
                    
                    wasm_emit_indented(ctx, 2, "    )\n");
                    wasm_emit_indented(ctx, 2, "  )\n");
                    wasm_emit_indented(ctx, 2, ")\n");
                    
                    // Skip to after the JMP and the exit label
                    i = jmp_idx + 1;
                    // Skip the exit label if present
                    if (i < instr_count && all_instrs[i]->opcode == IR_LABEL) i++;
                } else {
                    i++;  // Skip the label
                }
            } else {
                i++;  // Skip non-loop labels
            }
        } else if (instr->opcode == IR_JMP_IF) {
            // This is the start of an if statement (not a loop)
            // The condition is already on the stack from the previous comparison instruction

            // Find the next JMP instruction (skip to end of then block)
            int jmp_idx = -1;
            for (int j = i + 1; j < instr_count; j++) {
                if (all_instrs[j]->opcode == IR_JMP) {
                    jmp_idx = j;
                    break;
                }
            }

            // Find the else label (target of JMP_IF)
            const char *else_label = instr->label;

            // Determine if there's an else block
            int has_else = 0;
            if (else_label && jmp_idx >= 0) {
                // Check if there's a LABEL between JMP_IF and JMP with a different name
                for (int j = i + 1; j < jmp_idx; j++) {
                    if (all_instrs[j]->opcode == IR_LABEL && all_instrs[j]->label &&
                        strcmp(all_instrs[j]->label, else_label) == 0) {
                        has_else = 1;
                        break;
                    }
                }
            }

            // Emit the if instruction (note: WASM if executes then when condition is non-zero)
            wasm_emit_indented(ctx, 2, "(if\n");
            wasm_emit_indented(ctx, 2, "  (then\n");

            // Emit the then block (instructions after JMP_IF until else label or JMP)
            int j = i + 1;
            int last_was_restore = 0;
            while (j < instr_count && all_instrs[j]->opcode != IR_LABEL &&
                   all_instrs[j]->opcode != IR_JMP) {
                emit_instr(ctx, all_instrs[j]);
                last_was_restore = (all_instrs[j]->opcode == IR_RESTORE_X8_RESULT);
                j++;
            }
            
            // If the then block left a value on the stack (from post-increment/decrement),
            // drop it since if blocks shouldn't produce values
            if (last_was_restore) {
                wasm_emit_instr(ctx, "drop");
            }

            if (has_else) {
                wasm_emit_indented(ctx, 2, "  )\n");
                wasm_emit_indented(ctx, 2, "  (else\n");

                // Skip the else label and emit else block
                j++;  // Skip the else label
                while (j < instr_count && all_instrs[j]->opcode != IR_LABEL) {
                    if (all_instrs[j]->opcode != IR_JMP && all_instrs[j]->opcode != IR_JMP_IF) {
                        emit_instr(ctx, all_instrs[j]);
                    }
                    j++;
                }
            }

            wasm_emit_indented(ctx, 2, "  )\n");
            wasm_emit_indented(ctx, 2, ")\n");

            // Skip to after the end label
            while (i < instr_count && all_instrs[i]->opcode != IR_LABEL) i++;
            if (i < instr_count) i++;  // Skip the end label
        } else if (instr->opcode == IR_JMP) {
            // Skip unconditional jumps (handled by loop/if)
            i++;
        } else {
            // Emit regular instruction
            emit_instr(ctx, instr);
            i++;
        }
    }

    wasm_emit_indented(ctx, 2, ")\n");
    wasm_set_indent(ctx, 0);
}

void wasm_codegen_generate(IRModule *module, FILE *out) {
    if (!module || !out) return;
    
    current_module = module;  // Set for function index lookups
    reset_stack_ptr();  // Reset stack pointer for new module
    
    WasmContext *ctx = wasm_context_create(out);
    wasm_emit_module_header(ctx);
    
    // Detect imports
    if (module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            if (!func || !func->blocks) continue;
            for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
                IRBasicBlock *block = list_get(func->blocks, bi);
                if (!block || !block->instructions) continue;
                for (size_t ii = 0; ii < list_size(block->instructions); ii++) {
                    IRInstruction *instr = list_get(block->instructions, ii);
                    if (instr && instr->opcode == IR_CALL && instr->label) {
                        if (strcmp(instr->label, "printf") == 0) ctx->has_printf = true;
                        else if (strcmp(instr->label, "putchar") == 0) ctx->has_putchar = true;
                    }
                }
            }
        }
    }
    
    wasm_emit_imports(ctx);
    wasm_emit_memory(ctx);
    
    // Check if we need a function table for indirect calls
    ctx->needs_table = module_needs_table(module);
    if (ctx->needs_table) {
        wasm_emit_table(ctx, module);
    }
    
    wasm_emit_globals(ctx, module);
    
    if (module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            wasm_emit_function_header(ctx, func);
            wasm_emit_function_body(ctx, func);
            wasm_emit_function_footer(ctx);
        }
    }
    
    wasm_emit_exports(ctx, module);
    wasm_emit_module_footer(ctx);
    wasm_context_destroy(ctx);
}
