/**
 * wasm_codegen.c - WebAssembly code generation
 * 
 * Generates WebAssembly Text format (WAT) from IR module.
 */

#include "wasm_codegen.h"
#include "wasm_emit.h"
#include "../common/util.h"
#include "../common/list.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Forward declarations
static void emit_instruction(WasmContext *ctx, IRInstruction *instr);

// Block tracking for structured control flow
typedef struct BlockInfo {
    const char *label;
    int is_loop;
    int depth;
} BlockInfo;

static BlockInfo block_stack[64];
static int block_stack_top = 0;

// Create WASM codegen context
WasmContext *wasm_context_create(FILE *out) {
    WasmContext *ctx = xmalloc(sizeof(WasmContext));
    ctx->out = out;
    ctx->func_index = 0;
    ctx->string_index = 0;
    ctx->local_index = 0;
    ctx->label_count = 0;
    ctx->memory_pages = 2;  // 128KB default
    ctx->has_printf = false;
    ctx->has_putchar = false;
    block_stack_top = 0;
    return ctx;
}

// Destroy WASM codegen context
void wasm_context_destroy(WasmContext *ctx) {
    if (ctx) {
        free(ctx);
    }
    block_stack_top = 0;
}

// Get WASM type string for IR value
const char *wasm_type_for_ir_value(IRValue *val) {
    if (!val) return "i32";
    
    switch (val->kind) {
        case IR_VALUE_INT:
            return "i32";
        case IR_VALUE_FLOAT:
            return "f64";
        case IR_VALUE_PTR:
            return "i32";
        case IR_VALUE_STRING:
            return "i32";
        default:
            return "i32";
    }
}

// Emit module header
void wasm_emit_module_header(WasmContext *ctx) {
    wasm_emit(ctx, "(module\n");
    wasm_emit_comment(ctx, "Generated by c-compiler WASM backend");
    wasm_emit(ctx, "\n");
}

// Emit module footer
void wasm_emit_module_footer(WasmContext *ctx) {
    wasm_emit(ctx, ")\n");
}

// Emit memory declaration
void wasm_emit_memory(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, "(memory (export \"memory\") %d)\n", ctx->memory_pages);
    wasm_emit(ctx, "\n");
}

// Emit imports section
void wasm_emit_imports(WasmContext *ctx) {
    if (ctx->has_printf || ctx->has_putchar) {
        wasm_emit_comment(ctx, "Imports");
        
        if (ctx->has_printf) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"printf\" (func $printf (param i32 i32 i32 i32 i32) (result i32)))\n");
        }
        if (ctx->has_putchar) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"putchar\" (func $putchar (param i32) (result i32)))\n");
        }
        wasm_emit(ctx, "\n");
    }
}

// Emit exports section
void wasm_emit_exports(WasmContext *ctx, IRModule *module) {
    if (!module || !module->functions) return;
    
    wasm_emit_comment(ctx, "Exports");
    
    for (size_t i = 0; i < list_size(module->functions); i++) {
        IRFunction *func = list_get(module->functions, i);
        // Export main function and common entry points
        if (strcmp(func->name, "main") == 0) {
            wasm_emit_indented(ctx, 1, "(export \"main\" (func $main))\n");
            wasm_emit_indented(ctx, 1, "(export \"_main\" (func $main))\n");
        } else {
            wasm_emit_indented(ctx, 1, "(export \"%s\" (func $%s))\n", func->name, func->name);
            wasm_emit_indented(ctx, 1, "(export \"_%s\" (func $%s))\n", func->name, func->name);
        }
    }
}

// Emit function header
void wasm_emit_function_header(WasmContext *ctx, IRFunction *func) {
    if (!func) return;
    
    // Always emit result i32 for simplicity
    wasm_emit_indented(ctx, 1, "(func $%s (result i32)\n", func->name);
    
    // Emit locals - in a full implementation, we'd analyze the IR to determine needed locals
    wasm_emit_indented(ctx, 2, "(local $result i32)\n");
    wasm_emit_indented(ctx, 2, "(local $fp i32)\n");
    wasm_emit_indented(ctx, 2, "(local $sp i32)\n");
}

// Emit function footer
void wasm_emit_function_footer(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, ")\n");
}

// Emit function body with proper nested block structure
void wasm_emit_function_body(WasmContext *ctx, IRFunction *func) {
    if (!func || !func->blocks) return;
    
    wasm_set_indent(ctx, 2);
    block_stack_top = 0;
    
    // Collect all LABELs and their positions
    typedef struct {
        const char *label;
        size_t instr_idx;
        int is_loop;
    } LabelInfo;
    LabelInfo labels[64];
    int label_count = 0;
    
    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        
        for (size_t i = 0; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr->opcode == IR_LABEL && instr->label && label_count < 64) {
                labels[label_count].label = instr->label;
                labels[label_count].instr_idx = i;
                
                // Check if loop (backward jump)
                int is_loop = 0;
                for (size_t j = i + 1; j < list_size(block->instructions); j++) {
                    IRInstruction *later = list_get(block->instructions, j);
                    if (later && later->label && strcmp(later->label, instr->label) == 0) {
                        if (later->opcode == IR_JMP) {
                            is_loop = 1;
                            break;
                        }
                    }
                }
                labels[label_count].is_loop = is_loop;
                label_count++;
            }
        }
    }
    
    // Emit blocks in order, then instructions between them
    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        
        size_t last_label_idx = 0;
        for (int l = 0; l < label_count; l++) {
            // Emit instructions before this label
            for (size_t i = last_label_idx; i < labels[l].instr_idx && i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr && instr->opcode != IR_LABEL) {
                    emit_instruction(ctx, instr);
                }
            }
            
            // Emit block/loop
            if (labels[l].is_loop) {
                wasm_emit_indented(ctx, 2, "loop $%s\n", labels[l].label);
            } else {
                wasm_emit_indented(ctx, 2, "block $%s\n", labels[l].label);
            }
            if (block_stack_top < 64) {
                block_stack[block_stack_top].label = labels[l].label;
                block_stack[block_stack_top].is_loop = labels[l].is_loop;
                block_stack_top++;
            }
            
            last_label_idx = labels[l].instr_idx + 1;
        }
        
        // Emit remaining instructions after last label
        for (size_t i = last_label_idx; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr->opcode != IR_LABEL) {
                emit_instruction(ctx, instr);
            }
        }
    }
    
    // Close all blocks
    for (int i = block_stack_top - 1; i >= 0; i--) {
        wasm_emit_indented(ctx, 2, "end\n");
    }
    
    block_stack_top = 0;
    wasm_set_indent(ctx, 0);
}

// Emit a single instruction
static void emit_instruction(WasmContext *ctx, IRInstruction *instr) {
    if (!ctx || !instr) return;
    
    switch (instr->opcode) {
        case IR_NOP:
            wasm_emit_comment(ctx, "NOP");
            break;
            
        case IR_LABEL:
            // Labels are handled by block structure emission
            break;
            
        case IR_JMP:
            // Find the target label and calculate relative depth
            if (instr->label) {
                int depth = -1;
                for (int i = block_stack_top - 1; i >= 0; i--) {
                    if (strcmp(block_stack[i].label, instr->label) == 0) {
                        depth = block_stack_top - 1 - i;
                        break;
                    }
                }
                if (depth >= 0) {
                    wasm_emit_instr(ctx, "br %d", depth);
                } else {
                    wasm_emit_comment(ctx, "JMP to %s (label not found)", instr->label);
                }
            }
            break;
            
        case IR_JMP_IF:
            if (instr->num_args > 0 && instr->args[0]) {
                wasm_emit_value(ctx, instr->args[0]);
            }
            if (instr->label) {
                int depth = -1;
                for (int i = block_stack_top - 1; i >= 0; i--) {
                    if (strcmp(block_stack[i].label, instr->label) == 0) {
                        depth = block_stack_top - 1 - i;
                        break;
                    }
                }
                if (depth >= 0) {
                    wasm_emit_instr(ctx, "br_if %d", depth);
                } else {
                    wasm_emit_comment(ctx, "JMP_IF to %s (label not found)", instr->label);
                }
            }
            break;
            
        case IR_RET:
            if (instr->num_args > 0 && instr->args[0]) {
                wasm_emit_value(ctx, instr->args[0]);
            } else {
                wasm_emit_instr(ctx, "i32.const 0");
            }
            wasm_emit_instr(ctx, "return");
            break;
            
        case IR_RET_VOID:
            wasm_emit_instr(ctx, "return");
            break;
            
        case IR_CALL:
            if (instr->label) {
                if (strcmp(instr->label, "printf") == 0) {
                    ctx->has_printf = true;
                } else if (strcmp(instr->label, "putchar") == 0) {
                    ctx->has_putchar = true;
                }
            }
            for (int i = 0; i < instr->num_args && i < 5; i++) {
                if (instr->args[i]) {
                    wasm_emit_value(ctx, instr->args[i]);
                }
            }
            if (instr->label) {
                wasm_emit_instr(ctx, "call $%s", instr->label);
            }
            break;
            
        case IR_CONST_INT:
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                wasm_emit_const_int(ctx, instr->result->data.int_val);
            }
            break;
            
        case IR_ADD:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.add");
            }
            break;
            
        case IR_SUB:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.sub");
            }
            break;
            
        case IR_MUL:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.mul");
            }
            break;
            
        case IR_DIV:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.div_s");
            }
            break;
            
        // Bitwise operations
        case IR_AND:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.and");
            }
            break;
            
        case IR_OR:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.or");
            }
            break;
            
        case IR_XOR:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.xor");
            }
            break;
            
        case IR_SHL:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shl");
            }
            break;
            
        case IR_SHR:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shr_s");
            }
            break;
            
        case IR_NOT:
            if (instr->num_args >= 1) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_instr(ctx, "i32.eqz");
            }
            break;
            
        case IR_ALLOCA:
            break;
            
        case IR_STORE_PARAM:
            break;
            
        case IR_LOAD_STACK:
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                wasm_emit_instr(ctx, "local.get $result");
            }
            break;
            
        case IR_STORE_STACK:
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                wasm_emit_instr(ctx, "local.set $result");
            }
            break;
            
        case IR_LOAD:
            if (instr->num_args > 0 && instr->args[0]) {
                wasm_emit_value(ctx, instr->args[0]);
            }
            wasm_emit_instr(ctx, "i32.load");
            break;
            
        case IR_STORE:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[1]);  // value
                wasm_emit_value(ctx, instr->args[0]);  // address
            }
            wasm_emit_instr(ctx, "i32.store");
            break;
            
        case IR_CMP_LT:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.lt_s");
            }
            break;
            
        case IR_CMP_GT:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.gt_s");
            }
            break;
            
        case IR_CMP_LE:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.le_s");
            }
            break;
            
        case IR_CMP_GE:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.ge_s");
            }
            break;
            
        case IR_CMP_EQ:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.eq");
            }
            break;
            
        case IR_CMP_NE:
            if (instr->num_args >= 2) {
                wasm_emit_value(ctx, instr->args[0]);
                wasm_emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.ne");
            }
            break;
            
        default:
            wasm_emit_comment(ctx, "TODO: Implement opcode %d", instr->opcode);
            break;
    }
}

// Emit a value
void wasm_emit_value(WasmContext *ctx, IRValue *val) {
    if (!ctx || !val) return;
    
    switch (val->kind) {
        case IR_VALUE_INT:
            wasm_emit_const_int(ctx, val->data.int_val);
            break;
        case IR_VALUE_FLOAT:
            wasm_emit(ctx, "f64.const %f\n", val->data.float_val);
            break;
        case IR_VALUE_PTR:
        case IR_VALUE_STRING:
            wasm_emit_instr(ctx, "i32.const %d", val->string_index * 256);
            break;
        default:
            wasm_emit_comment(ctx, "Unknown value kind: %d", val->kind);
            break;
    }
}

// Emit constant integer
void wasm_emit_const_int(WasmContext *ctx, long long val) {
    if (!ctx) return;
    wasm_emit_instr(ctx, "i32.const %lld", val);
}

// Generate code for entire module
void wasm_codegen_generate(IRModule *module, FILE *out) {
    if (!module || !out) return;
    
    WasmContext *ctx = wasm_context_create(out);
    
    wasm_emit_module_header(ctx);
    wasm_emit_memory(ctx);
    wasm_emit_imports(ctx);
    
    // Emit functions
    if (module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            wasm_emit_function_header(ctx, func);
            wasm_emit_function_body(ctx, func);
            wasm_emit_function_footer(ctx);
        }
    }
    
    wasm_emit_exports(ctx, module);
    wasm_emit_module_footer(ctx);
    
    wasm_context_destroy(ctx);
}
