/**
 * wasm_codegen.c - WebAssembly code generation
 */

#include "wasm_codegen.h"
#include "wasm_emit.h"
#include "../common/util.h"
#include "../common/list.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

static int function_returns_void(IRFunction *func);

// Local variable tracking: maps stack offsets to WASM local indices
#define MAX_LOCALS 256
typedef struct {
    int offset;
    int local_index;
} LocalVar;
static LocalVar local_vars[MAX_LOCALS];
static int local_var_count = 0;
static int next_local_index = 0;  // Will be set to param_count + 1

static void reset_local_vars(int param_count) {
    local_var_count = 0;
    next_local_index = param_count;  // Start locals after parameters
}

static int get_or_create_local(int offset) {
    // Check if we already assigned a local for this offset
    for (int i = 0; i < local_var_count; i++) {
        if (local_vars[i].offset == offset) {
            return local_vars[i].local_index;
        }
    }
    // Assign a new local
    if (local_var_count < MAX_LOCALS) {
        local_vars[local_var_count].offset = offset;
        local_vars[local_var_count].local_index = next_local_index;
        local_var_count++;
        return next_local_index++;
    }
    return 0;  // Fallback
}

// Create WASM codegen context
WasmContext *wasm_context_create(FILE *out) {
    WasmContext *ctx = xmalloc(sizeof(WasmContext));
    ctx->out = out;
    ctx->func_index = 0;
    ctx->string_index = 0;
    ctx->local_index = 0;
    ctx->label_count = 0;
    ctx->memory_pages = 2;
    ctx->has_printf = false;
    ctx->has_putchar = false;
    ctx->stack_depth = 0;
    return ctx;
}

void wasm_context_destroy(WasmContext *ctx) {
    if (ctx) free(ctx);
}

void wasm_emit_module_header(WasmContext *ctx) {
    wasm_emit(ctx, "(module\n");
    wasm_emit_comment(ctx, "Generated by c-compiler WASM backend");
    wasm_emit(ctx, "\n");
}

void wasm_emit_module_footer(WasmContext *ctx) {
    wasm_emit(ctx, ")\n");
}

void wasm_emit_memory(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, "(memory (export \"memory\") %d)\n", ctx->memory_pages);
    wasm_emit(ctx, "\n");
}

void wasm_emit_imports(WasmContext *ctx) {
    if (ctx->has_printf || ctx->has_putchar) {
        wasm_emit_comment(ctx, "Imports");
        if (ctx->has_printf) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"printf\" (func $printf (param i32 i32 i32 i32 i32) (result i32)))\n");
        }
        if (ctx->has_putchar) {
            wasm_emit_indented(ctx, 1, "(import \"env\" \"putchar\" (func $putchar (param i32) (result i32)))\n");
        }
        wasm_emit(ctx, "\n");
    }
}

void wasm_emit_exports(WasmContext *ctx, IRModule *module) {
    if (!module || !module->functions) return;
    wasm_emit_comment(ctx, "Exports");
    for (size_t i = 0; i < list_size(module->functions); i++) {
        IRFunction *func = list_get(module->functions, i);
        if (strcmp(func->name, "main") == 0) {
            wasm_emit_indented(ctx, 1, "(export \"main\" (func $main))\n");
            wasm_emit_indented(ctx, 1, "(export \"_main\" (func $main))\n");
        } else {
            wasm_emit_indented(ctx, 1, "(export \"%s\" (func $%s))\n", func->name, func->name);
            wasm_emit_indented(ctx, 1, "(export \"_%s\" (func $%s))\n", func->name, func->name);
        }
    }
}

static int function_returns_void(IRFunction *func) {
    if (!func || !func->blocks) return 0;
    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        for (size_t i = 0; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr->opcode == IR_RET_VOID) return 1;
        }
    }
    return 0;
}

void wasm_emit_function_header(WasmContext *ctx, IRFunction *func) {
    if (!func) return;
    int param_count = 0;
    if (func->blocks) {
        for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
            IRBasicBlock *block = list_get(func->blocks, bi);
            if (!block || !block->instructions) continue;
            for (size_t i = 0; i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr && instr->opcode == IR_STORE_PARAM) {
                    int idx = instr->result->data.int_val;
                    if (idx >= 0 && idx >= param_count) param_count = idx + 1;
                }
            }
        }
    }
    if (param_count > 4) param_count = 4;
    
    int returns_void = function_returns_void(func);
    wasm_emit_indented(ctx, 1, "(func $%s", func->name);
    for (int i = 0; i < param_count; i++) wasm_emit(ctx, " (param $%d i32)", i);
    if (!returns_void) wasm_emit(ctx, " (result i32)");
    wasm_emit(ctx, "\n");
    for (int i = param_count; i < 8; i++) wasm_emit_indented(ctx, 2, "(local $%d i32)\n", i);
}

void wasm_emit_function_footer(WasmContext *ctx) {
    wasm_emit_indented(ctx, 1, ")\n");
}

// Emit a value
static void emit_value(WasmContext *ctx, IRValue *val) {
    if (!ctx || !val) return;
    if (val->emitted) return;
    
    switch (val->kind) {
        case IR_VALUE_INT:
            wasm_emit_instr(ctx, "i32.const %lld", val->data.int_val);
            val->emitted = true;
            break;
        case IR_VALUE_FLOAT:
            wasm_emit_instr(ctx, "f64.const %f", val->data.float_val);
            val->emitted = true;
            break;
        case IR_VALUE_PTR:
        case IR_VALUE_STRING:
            wasm_emit_instr(ctx, "i32.const %d", val->string_index * 256);
            val->emitted = true;
            break;
        default:
            if (val->param_reg >= 0 && val->param_reg < 8) {
                // This is a parameter
                wasm_emit_instr(ctx, "local.get $%d", val->param_reg);
            } else if (val->param_reg == -2) {
                // This is a local variable - map offset to local index
                int local = get_or_create_local(val->offset);
                wasm_emit_instr(ctx, "local.get $%d", local);
            } else {
                wasm_emit_instr(ctx, "local.get $0");
            }
            val->emitted = true;
            break;
    }
}

// Emit single instruction
static void emit_instr(WasmContext *ctx, IRInstruction *instr) {
    if (!ctx || !instr) return;
    
    switch (instr->opcode) {
        case IR_CONST_INT:
            if (instr->result && instr->result->kind == IR_VALUE_INT) {
                wasm_emit_instr(ctx, "i32.const %lld", instr->result->data.int_val);
                instr->result->emitted = true;
            }
            break;
            
        case IR_ADD:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.add");
            }
            break;
            
        case IR_SUB:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.sub");
            }
            break;
            
        case IR_MUL:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.mul");
            }
            break;
            
        case IR_DIV:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.div_s");
            }
            break;
            
        case IR_MOD:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.rem_s");
            }
            break;
            
        case IR_AND:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.and");
            }
            break;
            
        case IR_OR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.or");
            }
            break;
            
        case IR_XOR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.xor");
            }
            break;
            
        case IR_SHL:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shl");
            }
            break;
            
        case IR_SHR:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
                wasm_emit_instr(ctx, "i32.shr_s");
            }
            break;
            
        case IR_NOT:
            if (instr->num_args >= 1) {
                emit_value(ctx, instr->args[0]);
                wasm_emit_instr(ctx, "i32.eqz");
            }
            break;
            
        case IR_CMP_LT:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.lt_s");
            break;
            
        case IR_CMP_GT:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.gt_s");
            break;
            
        case IR_CMP_LE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.le_s");
            break;
            
        case IR_CMP_GE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.ge_s");
            break;
            
        case IR_CMP_EQ:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.eq");
            break;
            
        case IR_CMP_NE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[0]);
                emit_value(ctx, instr->args[1]);
            }
            wasm_emit_instr(ctx, "i32.ne");
            break;
            
        case IR_LOAD:
            if (instr->num_args > 0) emit_value(ctx, instr->args[0]);
            wasm_emit_instr(ctx, "i32.load");
            break;
            
        case IR_STORE:
            if (instr->num_args >= 2) {
                emit_value(ctx, instr->args[1]);
                emit_value(ctx, instr->args[0]);
                wasm_emit_instr(ctx, "i32.store");
            }
            break;
            
        case IR_LOAD_STACK:
            if (instr->result) {
                int local;
                if (instr->result->param_reg >= 0) {
                    // This is a parameter
                    local = instr->result->param_reg;
                } else {
                    // This is a local variable - map offset to local index
                    local = get_or_create_local(instr->result->offset);
                }
                wasm_emit_instr(ctx, "local.get $%d", local);
                instr->result->emitted = true;
            }
            break;
            
        case IR_STORE_STACK:
            if (instr->result) {
                // Store value from stack to local variable
                // The value should already be on the stack from previous instructions
                int local;
                if (instr->result->param_reg >= 0) {
                    // This is a parameter
                    local = instr->result->param_reg;
                } else {
                    // This is a local variable - map offset to local index
                    local = get_or_create_local(instr->result->offset);
                }
                wasm_emit_instr(ctx, "local.set $%d", local);
            }
            break;
            
        case IR_CALL:
            if (instr->label) {
                if (strcmp(instr->label, "printf") == 0) ctx->has_printf = true;
                else if (strcmp(instr->label, "putchar") == 0) ctx->has_putchar = true;
                for (int i = 0; i < instr->num_args && i < 5; i++) {
                    if (instr->args[i]) emit_value(ctx, instr->args[i]);
                }
                wasm_emit_instr(ctx, "call $%s", instr->label);
                // Mark the result as emitted (it's on the stack now)
                if (instr->result) instr->result->emitted = true;
            }
            break;
            
        case IR_RET:
            if (instr->num_args > 0 && instr->args[0]) emit_value(ctx, instr->args[0]);
            wasm_emit_instr(ctx, "return");
            break;
            
        case IR_RET_VOID:
            wasm_emit_instr(ctx, "return");
            break;

        case IR_SAVE_X8:
            // Save the current value on stack to a temp local WITHOUT popping
            // Uses local.tee which saves the value and leaves it on stack
            {
                static int temp_local = -1;
                if (temp_local < 0) temp_local = get_or_create_local(9999);  // Use offset 9999 for temp
                wasm_emit_instr(ctx, "local.tee $%d", temp_local);
            }
            break;

        case IR_ADD_X21:
            // Add the saved value (x21) to the current value (x8)
            {
                static int temp_local = -1;
                if (temp_local < 0) temp_local = get_or_create_local(9999);
                wasm_emit_instr(ctx, "local.get $%d", temp_local);
                wasm_emit_instr(ctx, "i32.add");
            }
            break;

        case IR_STORE_INDIRECT:
            // Store value to memory at address
            // Stack: [address, value] -> []
            // In WASM: i32.store
            wasm_emit_instr(ctx, "i32.store");
            break;

        case IR_RESTORE_X8_RESULT:
            // Restore the saved value (x22) to the stack
            // This is used for post-increment/decrement to return the original value
            {
                static int temp_local = -1;
                if (temp_local < 0) temp_local = get_or_create_local(9999);
                wasm_emit_instr(ctx, "local.get $%d", temp_local);
            }
            break;

        case IR_LEA:
            // Load effective address (sp + offset)
            // For WASM, this is just the offset value
            if (instr->result && instr->result->offset >= 0) {
                int local = get_or_create_local(instr->result->offset);
                wasm_emit_instr(ctx, "local.get $%d", local);
            } else {
                wasm_emit_instr(ctx, "i32.const 0");
            }
            break;

        default:
            // Skip other instructions
            break;
    }
}

void wasm_emit_function_body(WasmContext *ctx, IRFunction *func) {
    if (!func || !func->blocks) return;

    // Determine parameter count for this function
    int param_count = 0;
    if (func->blocks) {
        for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
            IRBasicBlock *block = list_get(func->blocks, bi);
            if (!block || !block->instructions) continue;
            for (size_t i = 0; i < list_size(block->instructions); i++) {
                IRInstruction *instr = list_get(block->instructions, i);
                if (instr && instr->opcode == IR_STORE_PARAM) {
                    int idx = instr->result->data.int_val;
                    if (idx >= 0 && idx >= param_count) param_count = idx + 1;
                }
            }
        }
    }

    // Reset local variable tracking with this function's parameter count
    reset_local_vars(param_count);

    wasm_set_indent(ctx, 2);
    int returns_void = function_returns_void(func);

    wasm_emit_indented(ctx, 2, "(block $exit%s\n", returns_void ? "" : " (result i32)");

    // Collect all instructions into a flat list for easier processing
    #define MAX_INSTRS 1024
    IRInstruction *all_instrs[MAX_INSTRS];
    int instr_count = 0;

    for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
        IRBasicBlock *block = list_get(func->blocks, bi);
        if (!block || !block->instructions) continue;
        for (size_t i = 0; i < list_size(block->instructions); i++) {
            IRInstruction *instr = list_get(block->instructions, i);
            if (instr && instr_count < MAX_INSTRS) {
                all_instrs[instr_count++] = instr;
            }
        }
    }

    // Process instructions, converting control flow to WASM if/else blocks
    int i = 0;
    while (i < instr_count) {
        IRInstruction *instr = all_instrs[i];

        if (instr->opcode == IR_JMP_IF) {
            // This is the start of an if statement
            // The condition is already on the stack from the previous comparison instruction
            // So we don't need to emit it again

            // Find the next JMP instruction (skip to end of then block)
            int jmp_idx = -1;
            for (int j = i + 1; j < instr_count; j++) {
                if (all_instrs[j]->opcode == IR_JMP) {
                    jmp_idx = j;
                    break;
                }
            }

            // Find the else label (target of JMP_IF)
            const char *else_label = instr->label;

            // Determine if there's an else block
            int has_else = 0;
            if (else_label && jmp_idx >= 0) {
                // Check if there's a LABEL between JMP_IF and JMP with a different name
                for (int j = i + 1; j < jmp_idx; j++) {
                    if (all_instrs[j]->opcode == IR_LABEL && all_instrs[j]->label &&
                        strcmp(all_instrs[j]->label, else_label) == 0) {
                        has_else = 1;
                        break;
                    }
                }
            }

            // Emit the if instruction (note: WASM if executes then when condition is non-zero)
            wasm_emit_indented(ctx, 2, "(if\n");
            wasm_emit_indented(ctx, 2, "  (then\n");

            // Emit the then block (instructions after JMP_IF until else label or JMP)
            int j = i + 1;
            int last_was_restore = 0;
            while (j < instr_count && all_instrs[j]->opcode != IR_LABEL &&
                   all_instrs[j]->opcode != IR_JMP) {
                emit_instr(ctx, all_instrs[j]);
                last_was_restore = (all_instrs[j]->opcode == IR_RESTORE_X8_RESULT);
                j++;
            }
            
            // If the then block left a value on the stack (from post-increment/decrement),
            // drop it since if blocks shouldn't produce values
            if (last_was_restore) {
                wasm_emit_instr(ctx, "drop");
            }

            if (has_else) {
                wasm_emit_indented(ctx, 2, "  )\n");
                wasm_emit_indented(ctx, 2, "  (else\n");

                // Skip the else label and emit else block
                j++;  // Skip the else label
                while (j < instr_count && all_instrs[j]->opcode != IR_LABEL) {
                    if (all_instrs[j]->opcode != IR_JMP && all_instrs[j]->opcode != IR_JMP_IF) {
                        emit_instr(ctx, all_instrs[j]);
                    }
                    j++;
                }
            }

            wasm_emit_indented(ctx, 2, "  )\n");
            wasm_emit_indented(ctx, 2, ")\n");

            // Skip to after the end label
            while (i < instr_count && all_instrs[i]->opcode != IR_LABEL) i++;
            if (i < instr_count) i++;  // Skip the end label
        } else if (instr->opcode == IR_LABEL || instr->opcode == IR_JMP) {
            // Skip labels and unconditional jumps (handled by if/else)
            i++;
        } else {
            // Emit regular instruction
            emit_instr(ctx, instr);
            i++;
        }
    }

    wasm_emit_indented(ctx, 2, ")\n");
    wasm_set_indent(ctx, 0);
}

void wasm_codegen_generate(IRModule *module, FILE *out) {
    if (!module || !out) return;
    
    WasmContext *ctx = wasm_context_create(out);
    wasm_emit_module_header(ctx);
    
    // Detect imports
    if (module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            if (!func || !func->blocks) continue;
            for (size_t bi = 0; bi < list_size(func->blocks); bi++) {
                IRBasicBlock *block = list_get(func->blocks, bi);
                if (!block || !block->instructions) continue;
                for (size_t ii = 0; ii < list_size(block->instructions); ii++) {
                    IRInstruction *instr = list_get(block->instructions, ii);
                    if (instr && instr->opcode == IR_CALL && instr->label) {
                        if (strcmp(instr->label, "printf") == 0) ctx->has_printf = true;
                        else if (strcmp(instr->label, "putchar") == 0) ctx->has_putchar = true;
                    }
                }
            }
        }
    }
    
    wasm_emit_imports(ctx);
    wasm_emit_memory(ctx);
    
    if (module->functions) {
        for (size_t i = 0; i < list_size(module->functions); i++) {
            IRFunction *func = list_get(module->functions, i);
            wasm_emit_function_header(ctx, func);
            wasm_emit_function_body(ctx, func);
            wasm_emit_function_footer(ctx);
        }
    }
    
    wasm_emit_exports(ctx, module);
    wasm_emit_module_footer(ctx);
    wasm_context_destroy(ctx);
}
